
-- ==================================================
-- SISTEMA DE PONTUAÇÃO E QUALIFICAÇÃO - HYDRAVIVE
-- ==================================================

-- 1. Tabela de Graduações
CREATE TABLE IF NOT EXISTS public.graduations (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    points_target integer NOT NULL,
    network_depth integer NOT NULL,
    reward text,
    level_order integer UNIQUE NOT NULL,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.graduations ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Inserir graduações base
INSERT INTO public.graduations (name, points_target, network_depth, reward, level_order) VALUES
('Afiliado', 0, 3, NULL, 0),
('Líder Sênior', 10000, 4, '1 Notebook', 1),
('Líder Executivo', 12000, 5, '1 Projetor', 2),
('Líder Master', 18000, 6, '1 Celular', 3),
('Coordenador', 25000, 7, '1 Viagem nacional com acompanhante', 4),
('Coordenador Premium', 35000, 8, '1 Cruzeiro nacional com acompanhante', 5),
('Coordenador Black', 50000, 9, '1 Moto 0km', 6),
('Black Diamond', 200000, 10, '1 Carro no valor de 100.000,00', 7)
ON CONFLICT (level_order) DO UPDATE SET 
    points_target = EXCLUDED.points_target,
    network_depth = EXCLUDED.network_depth,
    reward = EXCLUDED.reward,
    name = EXCLUDED.name;

-- 2. Atualizar affiliate_stats para incluir graduação atual
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'affiliate_stats' AND COLUMN_NAME = 'current_graduation_id') THEN
        ALTER TABLE public.affiliate_stats ADD COLUMN current_graduation_id bigint REFERENCES public.graduations(id);
    END IF;
END $$;

-- Definir graduação inicial para quem não tem
UPDATE public.affiliate_stats 
SET current_graduation_id = (SELECT id FROM public.graduations WHERE level_order = 0)
WHERE current_graduation_id IS NULL;

-- 3. Função de Fechamento Mensal
CREATE OR REPLACE FUNCTION public.process_monthly_closure()
RETURNS void AS $$
DECLARE
    affiliate RECORD;
    new_grad RECORD;
BEGIN
    FOR affiliate IN SELECT * FROM public.affiliate_stats LOOP
        -- Encontra a maior graduação que ele atingiu a meta
        SELECT * INTO new_grad 
        FROM public.graduations 
        WHERE points_target <= affiliate.monthly_points
        ORDER BY level_order DESC
        LIMIT 1;

        -- Se a nova graduação for maior que a atual, sobe de nível
        -- (O requisito diz: "se não continua no nível que está e recomeça")
        IF new_grad.level_order > (SELECT level_order FROM public.graduations WHERE id = affiliate.current_graduation_id) THEN
            UPDATE public.affiliate_stats 
            SET current_graduation_id = new_grad.id,
                updated_at = NOW()
            WHERE id = affiliate.id;
        END IF;
    END LOOP;

    -- Zerar pontos mensais para todos
    UPDATE public.affiliate_stats SET monthly_points = 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Atualizar process_mmn_commissions para distribuir pontos conforme qualificação
CREATE OR REPLACE FUNCTION public.process_mmn_commissions()
RETURNS TRIGGER AS $$
DECLARE
    current_sponsor_id BIGINT;
    current_level INTEGER := 1;
    commission_val NUMERIC;
    commission_type_val TEXT;
    commission_amount NUMERIC;
    sponsor_ref_code TEXT;
    v_total_points INTEGER := 0;
    v_sponsor_depth INTEGER;
BEGIN
    -- Só age se o status mudar para 'paid'
    IF (NEW.status = 'paid' AND (OLD.status IS NULL OR OLD.status <> 'paid')) THEN
        
        -- A. PROCESSAR PONTOS DO COMPRADOR (Se for afiliado)
        IF NEW.user_id IS NOT NULL THEN
            SELECT SUM(COALESCE(points_at_purchase, 0) * COALESCE(quantity, 1)) INTO v_total_points 
            FROM public.order_items WHERE order_id = NEW.id;

            IF v_total_points > 0 THEN
                INSERT INTO public.affiliate_stats (user_id) VALUES (NEW.user_id) ON CONFLICT (user_id) DO NOTHING;
                UPDATE public.affiliate_stats 
                SET points_balance = COALESCE(points_balance, 0) + v_total_points,
                    monthly_points = COALESCE(monthly_points, 0) + v_total_points,
                    updated_at = NOW()
                WHERE user_id = NEW.user_id;
            END IF;
        END IF;

        -- B. DEFINIR PONTO DE PARTIDA PARA REDE (Nível 1)
        IF NEW.affiliate_id IS NOT NULL THEN
            current_sponsor_id := NEW.affiliate_id;
        ELSE
            SELECT sponsor_id INTO current_sponsor_id 
            FROM public.user_profiles 
            WHERE id = NEW.user_id;
        END IF;

        -- C. SUBIR REDE
        WHILE current_sponsor_id IS NOT NULL AND current_level <= 10 LOOP
            
            -- Pega profundidade permitida da graduação atual do patrocinador
            SELECT g.network_depth INTO v_sponsor_depth
            FROM public.graduations g
            JOIN public.affiliate_stats s ON s.current_graduation_id = g.id
            WHERE s.user_id = current_sponsor_id;

            -- Se não tiver estatísticas ou graduação, assume default (3 níveis)
            IF v_sponsor_depth IS NULL THEN v_sponsor_depth := 3; END IF;

            -- 1. PROCESSAR PONTOS PARA O PATROCINADOR (Se estiver dentro da profundidade)
            IF current_level <= v_sponsor_depth AND v_total_points > 0 THEN
                UPDATE public.affiliate_stats 
                SET points_balance = COALESCE(points_balance, 0) + v_total_points,
                    monthly_points = COALESCE(monthly_points, 0) + v_total_points,
                    updated_at = NOW()
                WHERE user_id = current_sponsor_id;
            END IF;

            -- 2. PROCESSAR COMISSÃO FINANCEIRA (Regra Existente)
            SELECT amount, COALESCE(commission_type, 'percentage') INTO commission_val, commission_type_val 
            FROM public.cashback_config 
            WHERE level = current_level AND is_active = true;
            
            SELECT referral_code INTO sponsor_ref_code FROM public.user_profiles WHERE id = current_sponsor_id;

            IF commission_val IS NOT NULL AND commission_val > 0 AND sponsor_ref_code IS NOT NULL THEN
                -- Cálculo
                IF commission_type_val = 'fixed' THEN
                    commission_amount := commission_val;
                ELSE
                    commission_amount := (NEW.total_amount * commission_val) / 100;
                END IF;

                -- Atualiza Saldo
                UPDATE public.affiliate_stats 
                SET total_earnings = COALESCE(total_earnings, 0) + commission_amount,
                    available_balance = COALESCE(available_balance, 0) + commission_amount,
                    updated_at = NOW()
                WHERE user_id = current_sponsor_id;

                -- Registra Extrato
                INSERT INTO public.commissions (order_id, affiliate_id, amount, level, status, created_at)
                VALUES (NEW.id, current_sponsor_id, commission_amount, current_level, 'released', NOW());
            END IF;

            -- Próximo da rede
            SELECT sponsor_id INTO current_sponsor_id FROM public.user_profiles WHERE id = current_sponsor_id;
            current_level := current_level + 1;
        END LOOP;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. SEGURANÇA (RLS)
ALTER TABLE public.graduations ENABLE ROW LEVEL SECURITY;

-- Permite que qualquer usuário autenticado veja as graduações
DROP POLICY IF EXISTS "Qualquer um pode ver graduações" ON public.graduations;
CREATE POLICY "Qualquer um pode ver graduações" ON public.graduations 
FOR SELECT TO authenticated USING (true);

-- Permite que apenas admins gerenciem as graduações
DROP POLICY IF EXISTS "Admins gerenciam graduações" ON public.graduations;
CREATE POLICY "Admins gerenciam graduações" ON public.graduations 
FOR ALL TO authenticated USING (
    EXISTS (
        SELECT 1 FROM public.user_profiles 
        WHERE mocha_user_id = auth.uid()::text 
        AND role = 'admin'
    )
);

-- Garantir que a trigger de atualização de pontos também tenha permissão
GRANT ALL ON public.graduations TO postgres, service_role;
GRANT ALL ON public.affiliate_stats TO postgres, service_role;

